baseURL = "/"
author = ""
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# Above are configs from hugoBasicExample

title = "Pet Shop for All"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 10
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname=""
copyright = "&copy; 2021"




[params]
description = ""
twitter = ""
useIcon = false
useTwitterCard = true
# exampleSite must not have js share widget: #36
# shareTo = ["Twitter", "Hatena", "Facebook", "Pocket"]
shareTo = []
showFooterCredits = true
math = true

[[menu.main]]
name = "Pet Supplies"
URL = "/"
weight = 1



[[menu.main]]
name = "Pet Supplies"
URL = "/pet-supplies"
weight = 0
parent = "Pet Supplies"

[[menu.main]]
name = "/cat-trees"
URL = "/cat-trees"
weight = 0
parent = "Pet Supplies"



[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = true
  email = true
